// =============================================================================
// HYDRA-UMC DSI (Flutter) - ui/settings_screen.dart
// Copyright (C) 2026 JuanenRac (Electro Hobby 3D) <electrohobby3d@gmail.com>
// GPL-3.0 - see LICENSE
//
// Ported from HYDRA-UMC-IOS-CONTROL's own ui/settings_screen.dart, with
// the discovery/hostname fields from hydraInfo (see
// state/robot_view_model.dart) added since this screen doubles as the
// "about this connection" view a kiosk operator would otherwise have no
// way to reach.
//
// The "HYDRA-UMC DSI version" tile at the bottom is this app's OWN client
// version (from lib/app_version.dart, regenerated by
// tool/bump_version.dart on every real build - see build.sh/build.bat/
// build_linux.sh) - not to be confused with the "App version" tile above
// it inside the hydraInfo block, which reports the CONNECTED SERVER's
// (HYDRA-UMC-STUDIO's) own version. Same distinction and same bottom
// placement HYDRA-UMC-IOS-CONTROL uses in its own settings_screen.dart.
// =============================================================================

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../app_version.dart';
import '../l10n/app_localizations.dart';
import '../state/robot_view_model.dart';

class SettingsScreen extends StatelessWidget {
  const SettingsScreen({super.key});

  static String _connectionStatusLabel(AppLocalizations l10n, String status) {
    switch (status) {
      case 'connected':
        return l10n.connStatusConnected;
      case 'connecting':
        return l10n.connStatusConnecting;
      case 'error':
        return l10n.connStatusError;
      case 'disconnected':
      default:
        return l10n.connStatusDisconnected;
    }
  }

  static String _languageDisplayName(String code) {
    switch (code) {
      case 'es':
        return 'Español';
      case 'fr':
        return 'Français';
      case 'de':
        return 'Deutsch';
      case 'it':
        return 'Italiano';
      case 'ja':
        return '日本語';
      case 'zh':
        return '简体中文';
      case 'en':
      default:
        return 'English';
    }
  }

  @override
  Widget build(BuildContext context) {
    final vm = context.watch<RobotViewModel>();
    final l10n = AppLocalizations.of(context)!;
    final server = vm.activeServer;
    final info = vm.hydraInfo;
    return ListView(
      padding: const EdgeInsets.all(20),
      children: [
        ListTile(
          leading: const Icon(Icons.dns),
          title: Text(server?.displayName ?? l10n.settingsNotConnected),
          subtitle: Text(server != null ? '${server.host}:${server.port}' : ''),
        ),
        ListTile(
          leading: const Icon(Icons.wifi_tethering),
          title: Text(l10n.settingsStatus(_connectionStatusLabel(l10n, vm.connectionStatus))),
        ),
        if (info != null) ...[
          ListTile(leading: const Icon(Icons.dns_outlined), title: Text(l10n.settingsProduct('${info['product'] ?? '?'}'))),
          ListTile(leading: const Icon(Icons.numbers), title: Text(l10n.settingsRemoteApiVersion('${info['remoteApiVersion'] ?? '?'}'))),
          ListTile(leading: const Icon(Icons.tag), title: Text(l10n.settingsAppVersion('${info['appVersion'] ?? '?'}'))),
        ],
        const Divider(),
        ListTile(
          leading: const Icon(Icons.language),
          title: Text(l10n.settingsLanguage),
          trailing: DropdownButton<String?>(
            value: vm.languageOverride?.languageCode,
            underline: const SizedBox.shrink(),
            items: [
              DropdownMenuItem<String?>(value: null, child: Text(l10n.settingsLanguageSystem)),
              for (final locale in AppLocalizations.supportedLocales)
                DropdownMenuItem<String?>(
                  value: locale.languageCode,
                  child: Text(_languageDisplayName(locale.languageCode)),
                ),
            ],
            onChanged: (code) => vm.setLanguage(code),
          ),
        ),
        const Divider(),
        ListTile(
          leading: const Icon(Icons.logout, color: Colors.redAccent),
          title: Text(l10n.settingsSignOut),
          onTap: () => vm.logout(),
        ),
        const Divider(),
        ListTile(
          leading: const Icon(Icons.info_outline),
          title: Text(l10n.settingsDsiVersion),
          subtitle: const Text('$kAppVersion (build $kAppBuildNumber)'),
        ),
      ],
    );
  }
}
